name: Empleos de Call Center
favicon: null
layout_spectrum: 0.75124
typography_spectrum: 0.73144
title: Empleos de Call Center
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72650005-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6780378594994545
  lightness: 0.7443621593993157
  saturation: 0.7742176712490618
  rhythmicContrast: 0.4509963118471205
purpose: []
